FROM ruby:3.3.4

#RUN apk add --no-cache git build-base libxml2-dev libxslt-dev tzdata bash less vim postgresql-dev postgresql-client
RUN apt install gcc make libpq-dev
#WORKDIR /rails_app
#COPY /rails_app/Gemfile .
#COPY /rails_app/Gemfile.lock .
#RUN gem update --system && \
#    bundle install
